version: '3'

services:
  mysqldatabase:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=test1234
      - MYSQL_DATABASE=products_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=test1234
    networks:
      - fullstack
    container_name: mysql_database_container
  products-container:
    image: catalogue
    depends_on:
      - mysqldatabase
    ports:
      - 8081:8081
    networks:
      - fullstack
    container_name: catalogue_container
networks:
  fullstack: